# Generated by Django 4.1.3 on 2022-12-12 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre_instructor')),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=12, verbose_name='fono_instructor')),
                ('runInstructor', models.CharField(max_length=13, verbose_name='run_instructor')),
                ('genero', models.IntegerField(choices=[[0, 'femenino'], [1, 'masculino'], [2, 'otro']])),
                ('certificado', models.FileField(null=True, upload_to='certificados/', verbose_name='certificado')),
            ],
        ),
    ]
