# Generated by Django 4.1.3 on 2022-12-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='certificado',
            field=models.FileField(null=True, upload_to='', verbose_name='certificado'),
        ),
    ]
