# Generated by Django 4.1.3 on 2022-12-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_instructor_certificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='certificado',
            field=models.CharField(max_length=100, null=True, verbose_name='certificado'),
        ),
    ]
